apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: istioinit-gke
  namespace: default
spec:
  template:
    metadata:
      name: istioinit-gke-0001
    spec:
      containers:
      - image: gcr.io/mineral-minutia-820/istioinit:1